Added skip props flag
doma-engineering/type_class pull request #1
Opened 2022-10-25 16:03 UTC by maslowalex

2022-10-25 16:23 UTC, cognivore approved these changes
LGTM! If you have tested the changes, feel free to merge!

2022-10-26 18:25 UTC, cognivore requested changes

2022-10-26 18:25 UTC, cognivore commented on lib/type_class.ex
> +          # IO.warn("""
I think that this should be another configuration option + ENV option.

2022-11-12 13:18 UTC, cognivore commented
https://github.com/witchcrafters/type_class/commit/ddd369949654e413a948be1d4ed1fc4b259f2f7c

Just checking in that you've added logic like this.

2022-11-12 13:49 UTC, maslowalex commented
> 

Should we add call to `Application` env too? Like with `force_type_class`?

2022-11-12 13:57 UTC, cognivore commented on lib/type_class.ex
> +				# @doc "Force type classes by default, but accept configuration options based on FORCE_TYPE_CLASS env variable and :doma_type_class > :force_type_class configuration path."
Something happened to the indentation here.

2022-11-12 14:00 UTC, cognivore requested changes

2022-11-12 14:00 UTC, cognivore commented on lib/type_class.ex
> +        _ -> true
You have to make sure that your changes agree with each other.

The new default behaviour is to skip compile time tests (FORCE_TYPE_CLASS = true is default).

To match this new behaviour, you have to either:

 - Default PRINT_WARNINGS to false.
 - Rename PRINT_WARNINGS to NOWARN_FORCED_TYPE_CLASS and default it to true (symmetric with the FORCE_TYPE_CLASS).

2022-11-12 14:00 UTC, cognivore commented on lib/type_class.ex
> +          if print_warnings do
Would be cool to have this as a configuration option too, just as the FORCE_TYPE_CLASS is.

2022-11-12 14:02 UTC, cognivore requested changes
- Match the semantics of these changes with the `FORCE_TYPE_CLASS`
 - Add a low_priority configuration option here, analogously with `FORCE_TYPE_CLASS`
 - Fix indentation in the `force_type_class_const` computation.

2022-11-13 01:11 UTC, cognivore approved these changes

2022-11-24 12:00 UTC, merged